# Generated by Django 3.2.3 on 2021-06-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='CoolerGpu',
            fields=[
                ('idCooler', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id de Cooler')),
                ('TamañoCGPU', models.CharField(max_length=3, verbose_name='Tamño Cooler')),
                ('ColorCGPU', models.CharField(max_length=10, verbose_name='Color Cooler')),
                ('NombreCooler', models.CharField(max_length=30, verbose_name='Nombre Cooler')),
            ],
        ),
        migrations.CreateModel(
            name='FuentePoder',
            fields=[
                ('idFuentePoder', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id de Fuente de Poder')),
                ('PotenciaFP', models.CharField(max_length=10, verbose_name='Potencia de fuente de poder en V')),
                ('MarcaFP', models.CharField(max_length=30, verbose_name='Marca de fuente de poder')),
                ('ModeloFP', models.CharField(max_length=30, verbose_name='Modelo Funte de poder')),
                ('NombreFuente', models.CharField(max_length=30, verbose_name='Nombre de fuente de poder')),
            ],
        ),
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('idGabinete', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='id del Gabinete')),
                ('TamañoGB', models.CharField(max_length=10, verbose_name='Potencia')),
                ('MarcaGB', models.CharField(max_length=30, verbose_name='marca')),
                ('NombreGabinete', models.CharField(max_length=30, verbose_name='Nombre de fuente de poder')),
                ('ColorGB', models.CharField(max_length=10, verbose_name='Color Gabinete')),
                ('ModeloGB', models.CharField(max_length=30, verbose_name='Modelo gabinete')),
            ],
        ),
        migrations.CreateModel(
            name='PlacaMadre',
            fields=[
                ('idPM', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id de la placa madre')),
                ('ModeloPM', models.CharField(max_length=20, verbose_name='Modelo placa madre')),
                ('MarcaPM', models.CharField(max_length=20, verbose_name='Marca placa madre')),
                ('CaracteristicasPM', models.CharField(max_length=100, verbose_name='Caracteristicas de placa madre')),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('idPR', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id de el procesador')),
                ('ModeloPR', models.CharField(max_length=20, verbose_name='Modelo de procesador')),
                ('MarcaPR', models.CharField(max_length=20, verbose_name='Marca procesador')),
                ('CaracteristicasPR', models.CharField(max_length=100, verbose_name='Caracteristicas procesador')),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('idRAM', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id de la la ram')),
                ('MarcaRAM', models.CharField(max_length=20, verbose_name='Marca memoria ram')),
                ('ModeloRAM', models.CharField(max_length=30, verbose_name='Modelo de memoria ram ')),
                ('CaracteristicasRAM', models.CharField(max_length=40, verbose_name='Caracteristicas de la memoria ram')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaGrafica',
            fields=[
                ('idTJ', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id de la la tarjeta grafica')),
                ('MarcaTJ', models.CharField(max_length=20, verbose_name='Marca de la tarjeta grafica')),
                ('ModeloTJ', models.CharField(max_length=30, verbose_name='Modelo de la tarjeta grafica ')),
                ('CaracteristicasTJ', models.CharField(max_length=40, verbose_name='Caracteristicas de la tarjeta grafica')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadAlmacenamiento',
            fields=[
                ('idAlmacenamiento', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id de el Almacenamiento')),
                ('tamañoGB', models.CharField(max_length=10, verbose_name='Tamaño en GB')),
                ('MarcaUA', models.CharField(max_length=30, verbose_name='Marca de unidad de almacenamiento')),
                ('ModeloUA', models.CharField(max_length=30, verbose_name='Modelo Unidad de almacenamiento')),
            ],
        ),
    ]
